version: '3'
services:
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
    ports:
      - '3306:3306'
    networks:
      - my-network
    volumes:
      - db:/var/lib/mysql
networks:
  my-network:
    driver: bridge
volumes:
  db:
